version: '3.9'
services:
  app:
    build: .
    container_name: app
    restart: always
    ports:
      - 8000:8000
    networks:
      - default

networks:
  default:
    name: docker_trust_sign_network
    driver: bridge

volumes:
  data:
    name: docker_trust_sign_data
    driver: local
